---

- name: Install psad
  apt:
    name: "{{ item }}"
  with_items:
    - psad
    - fwsnort

- name: Configure psad
  template:
    src: "psad.conf.j2"
    dest: "/etc/psad/psad.conf"
    mode: 0640
    owner: root
    group: root
  notify: [ 'Restart psad' ]

- name: Set exceptions auto_dl
  lineinfile:
    dest: /etc/psad/auto_dl
    line: "{{ item }};"
  with_flattened:
    - service_psad_auto_dl
    - service_psad_auto_dl_group
    - service_psad_auto_dl_host
  notify: [ 'Restart psad' ]

- name: Set defaults in /etc/defaults
  lineinfile:
    dest: '/etc/default/psad'
    insertafter: EOF
    line: 'DAEMON_ARGS="-no-rdns --no-whois"'
